config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  namespace :api, defaults: { format: :json } do
    resources :tasks

    put 'tasks/:id/complete', to: 'tasks#complete'
    put 'tasks/:id/uncomplete', to: 'tasks#uncomplete'

    put 'tasks/:id/start', to: 'tasks#start_timer'
    put 'tasks/:id/stop', to: 'tasks#stop_timer'
  end

  root to: 'application#index'
  match '*path', to: 'application#index', via: :get
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  belongs_to :user
  has_many :timelogs, -> { order('id') }
  validates :title, presence: true

  def start_timer
    # if has old timer, stop it first
    Timelog.where({ task_id: id, end_time: nil }).update(end_time: DateTime.current) if active_timer?
    # create new time log
    timelogs.create
  end

  def stop_timer
    timelogs.last.update(end_time: DateTime.current)
  end

  def active_timer?
    timelogs.last&.end_time.nil?
  end
end

app/models/timelog.rb
# frozen_string_literal: true

class Timelog < ApplicationRecord
  belongs_to :task

  def duration
    return false if end_time.nil?

    ((end_time - start_time) / 60).to_i
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
end

app/controllers/api/tasks_controller.rb
# frozen_string_literal: true

module Api
  class TasksController < ApplicationController
    before_action :authenticate_user!
    before_action :set_task, only: %i[show update destroy complete uncomplete start_timer stop_timer]

    # GET /tasks or /tasks.json
    def index
      @tasks = current_user.tasks.includes(:timelogs).all
      render json: @tasks.map { |task| TaskPresenter.new(task).present }
    end

    # GET /tasks/1 or /tasks/1.json
    def show
      render json: TaskPresenter.new(@task).present
    end

    # POST /tasks or /tasks.json
    def create
      @task = current_user.tasks.new(task_params)

      if @task.save
        render :show, status: :created, location: @task
      else
        render json: @task.errors, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /tasks/1 or /tasks/1.json
    def update
      if @task.update(task_params)
        render :show, status: :ok, location: @task
      else
        render json: @task.errors, status: :unprocessable_entity
      end
    end

    # DELETE /tasks/1 or /tasks/1.json
    def destroy
      @task.destroy

      head :no_content
    end

    def complete
      @task.update({ completed: true })
    end

    def uncomplete
      @task.update({ completed: false })
    end

    def start_timer
      @task.start_timer
    end

    def stop_timer
      @task.stop_timer
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = current_user.tasks.includes(:timelogs).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :content, :completed, :due_date)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/application/index.html.erb
<div class="container" style="max-width: 800px">
  <div id="app"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Tasks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_stylesheet_tag 'application.scss' %>
    <%= vite_javascript_tag 'application.js' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %> 
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :content, class: 'form-label' %> 
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.check_box :completed, class: 'form-check-input' %>
    <%= form.label :completed, class: 'form-check-label' %> 
  </div>

  <div class="mb-3">
    <%= form.label :due_date, class: 'form-label' %> 
    <%= form.datetime_select :due_date, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="container" style="max-width: 800px">
  <div id="app"></div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>